In [6]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('datasets/dataset_train.csv')

In [11]:
data.drop('Index', axis=1,
          inplace=True)

In [13]:
data_num = data.select_dtypes(include = np.number)

In [31]:
describe = pd.DataFrame(index = range(8),
                        columns=range(len(data_num.columns)))

In [32]:
describe.index = ['Count',
                  'Mean',
				  'Std',
                  'Min',
                  '25%',
                  '50%',
                  '75%',
                  'Max']

In [33]:
describe.columns = data_num.columns

In [109]:
for i in range(len(describe.columns)):
	# Count
	describe.iloc[0, i] = data_num.iloc[:, i].notnull().sum()
	# Mean
	describe.iloc[1, i] = np.sum(data_num.iloc[:, i]) / describe.iloc[0, i]
	# Standard deviation
	describe.iloc[2, i] = np.sqrt(np.sum((data_num.iloc[:, i] - describe.iloc[1, i]) ** 2) / (describe.iloc[0, i] - 1))
	# Minimum
	describe.iloc[3, i] = data_num.iloc[0, i]
	for j in range(len(data_num.iloc[:, i])):
		if data_num.iloc[j, i] < describe.iloc[3, i]:
			describe.iloc[3, i] = data_num.iloc[j, i]
	# First quartile
	describe.iloc[4, i] = data_num.iloc[:, i].sort_values().iloc[int((describe.iloc[0, i] + 1) / 4)]
	# Second quartile
	describe.iloc[5, i] = data_num.iloc[:, i].sort_values().iloc[int((describe.iloc[0, i] + 1) / 2)]
	# Third quartile
	describe.iloc[6, i] = data_num.iloc[:, i].sort_values().iloc[3 * int((describe.iloc[0, i] + 1) / 4)]
	# Maximum
	describe.iloc[7, i] = data_num.iloc[0, i]
	for j in range(len(data_num.iloc[:, i])):
		if data_num.iloc[j, i] > describe.iloc[7, i]:
			describe.iloc[7, i] = data_num.iloc[j, i]

In [110]:
describe

,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
Count,1566,1568,1567,1569,1561,1565,1565,1557,1566,1570,1560,1600,1600
Mean,49634.570243,39.797131,1.14102,-0.387863,3.15391,-224.589915,495.74797,2.963095,1030.096946,5.950373,-0.053427,-243.374409,21.958012
Std,16679.806036,520.298268,5.219682,5.212794,4.155301,486.34484,106.285165,4.425775,44.125116,3.147854,0.971457,8.78364,97.631602
Min,-24370.0,-966.740546,-10.295663,-10.162119,-8.727,-1086.496835,283.869609,-8.858993,906.62732,-4.697484,-3.313676,-261.04892,-181.47
25%,38510.0,-489.493777,-4.304245,-5.259095,3.099,-577.580096,397.511047,2.218653,1026.171713,3.6449,-0.670996,-250.64727,-41.84
50%,49018.0,261.644731,3.486307,-2.572919,4.625,-418.660994,464.327598,4.379618,1045.533335,5.877582,-0.043296,-244.86751,-2.51
75%,60761.0,525.90954,5.423167,4.90468,5.667,254.994857,597.49223,5.825242,1058.409478,8.246324,0.594446,-232.53675,50.89
Max,104956.0,1016.21194,11.612895,9.667405,10.032,1092.388611,745.39622,11.889713,1098.958201,13.536762,3.056546,-225.42814,279.07